### ISSUE TITLE
Renders textures in wrong order.

### ISSUE THREAD

**Issue by Mikecolle** [Asek3/Oculus#541] opened 2024-02-02 03:53 UTC
### What happened?

Okay, to give a bit more context, the top picture is the intended way for the BlockEntity to be rendered, the bottom picture is what happens with Oculus installed:
![293354259-91aace99-3753-45b3-b565-aca0c6c6541b](https://github.com/Asek3/Oculus/assets/29614860/30c5b916-48e6-4f9c-aa82-11905edb4979)
![293354265-d86bf192-e5b4-4fb5-8db4-ded6d6983d10](https://github.com/Asek3/Oculus/assets/29614860/9f7065cf-fc4a-41d6-9def-435d747802a6)

From what I've gathered surrounding what is going on:
The block entity is rendering not through json models and voxels, but rather through various quads and vertexes.
The way it's designed, there is a base layer (which is being rendered correctly) and an overlay layer (which is created in the exact same way as the base layer, down to its size, but it's using a different texture and render type). Normally, the second layer would be rendered after the base layer, but when Oculus is installed, the second layer always renders before the first layer, causing the effect in which it seems like only the base layer is being rendered and the other one isn't.

I've tested it by creating a resourcepack that gives the base layer a transparent texture and sure enough, the second layer is still being rendered, but obviously under the base layer.

### Minecraft Version

1.18.2, 1.19.2, 1.20.1

### Oculus Version

1.6.13 and up

### Rubidium / Embeddium Version

current

### Operating System

win 10

### What is your GPU?

Rtx 3060 + GTX 1650 Super

### Java Version

17

**Comment by dima-dencep** [comment] 2024-02-02 05:34
Duplicate of #522

**Closed as not planned by dima-dencep** 2024-02-02 05:34 UTC
Labels: bug, invalid
