### ISSUE TITLE
1.20.1 glass is not allowing sunlight to go through when using the shader comp unbound

### ISSUE THREAD

**Issue by Thunderrock424242** [Asek3/Oculus#486] opened 2023-11-04 01:30 UTC
### What happened?

sunlight can't pass through glass

### Screenshots

<img width="1266" alt="Screenshot 2023-11-03 212636" src="https://github.com/Asek3/Oculus/assets/119463825/2e98c508-2718-4621-bb34-69f4279e349f">
<img width="1275" alt="Screenshot 2023-11-03 212804" src="https://github.com/Asek3/Oculus/assets/119463825/685f4e3d-d828-4fbb-a9ac-18ba3a72f092">

### Minecraft Version

1.20.1

### Oculus Version

1.6.9

### Rubidium Version

n/a using embedium

### Operating System

windows 11

### What is your GPU?

nivida geforce rtx 4060 laptop

### Java Version

java 17 i think

**Comment by gaussandhisgun** [comment] 2023-11-04 07:50
this is a shader bug, try enabling stuff like colored shadows

**Comment by Thunderrock424242** [comment] 2023-11-04 15:27
> this is a shader bug, try enabling stuff like colored shadows

The shader dev says it's a ocuals issue and iris does not have it

**Comment by MoonDew** [comment] 2023-11-19 21:25
> > this is a shader bug, try enabling stuff like colored shadows
> 
> The shader dev says it's a ocuals issue and iris does not have it

When will it get fixed?  I can't use things like glass domes and glass roofs if they're going to cast shadows like this?

**Comment by PlayfulPiano** [comment] 2023-12-03 00:15
![image](https://github.com/Asek3/Oculus/assets/3158887/02064064-597a-478c-a59c-6bb3c7d06a2f)
can also confirm that oculus causes glass to apply a shadow when using complementary shaders. Using forge 1.20.1 with embeddium beta and oculus 1.6.9 1.20.1.

**Comment by PlayfulPiano** [comment] 2023-12-03 00:52
IMS figured out the issue:
![image](https://github.com/Asek3/Oculus/assets/3158887/3f477ac5-c4ad-4c19-bb11-8ccc37b06e81)

**Comment by Shadowdane** [comment] 2023-12-03 17:53
This issue also happens on Oculus 1.18.2-1.6.4.   So it's not exclusive to just 1.20.1.    Been playing Vault Hunters with shaders and noticed that light doesn't pass through glass.

**Minecraft Version**
1.18.2

**Oculus Version**
1.6.4

**Rubidium Version**
0.5.6

**Operating System**
windows 11

**What is your GPU?**
Nvidia RTX 4080

**Java Version**
17.0.9

**Forge Version**
40.2.9



![2023-12-03_12 30 04](https://github.com/Asek3/Oculus/assets/43715181/c5aaaaf0-820c-41cd-910c-7913d8a181f3)

**Comment by embeddedt** [comment] 2023-12-20 23:18
Please check if this is fixed when using 1.6.13.

**Comment by Thunderrock424242** [comment] 2023-12-21 00:51
I will test it out when I get a chance

**Comment by Thunderrock424242** [comment] 2023-12-21 03:16
> Please check if this is fixed when using 1.6.13.

Pretty sure it's fixed I tested it and looks good

**Comment by Shadowdane** [comment] 2023-12-21 15:49
> Please check if this is fixed when using 1.6.13.

Will this fix be ported back to the 1.18.2 build as well?
Or should I fill a different bug report for that version specifically?

**Comment by embeddedt** [comment] 2023-12-21 15:50
I'm not sure 1.18 will receive another update.

**Comment by GarthF** [comment] 2024-01-03 18:51
I'm running 1.6.13 and still have the shadowed glass issue.

![image](https://github.com/Asek3/Oculus/assets/13380578/b79ad942-96dd-4187-a38c-e47fb5df9152)

**Comment by Thunderrock424242** [comment] 2024-01-03 18:56
Damn

**Comment by PlayfulPiano** [comment] 2024-01-03 22:51
damn

**Comment by embeddedt** [comment] 2024-01-03 22:52
@GarthF What shader are you using?

**Comment by GarthF** [comment] 2024-01-04 06:37
Complementary Shaders, both unbound and reimagined show the issue. Using them on the direwolf20 pack.
Unbound r5.1.1
Reimagined r5.1.1

Interestingly the cyclic clear glass is unaffected. 
![image](https://github.com/Asek3/Oculus/assets/13380578/aa89e759-259d-4dd1-ba26-daa8d95e7cb2)

**Comment by embeddedt** [comment] 2024-01-04 15:48
So I'm unable to reproduce this in a standalone instance, but if you can only get it to happen in a large modpack I have an idea of what the issue might be. Can you try this version and let me know if the behavior is any different? 

[oculus-testing.zip](https://github.com/Asek3/Oculus/files/13832233/oculus-testing.zip)

**Comment by GarthF** [comment] 2024-01-04 20:51
Ran the test Jar, unfortunately still seeing same shadow effect: 
![image](https://github.com/Asek3/Oculus/assets/13380578/63b7f109-be13-4960-9ea9-7076e279ba5a)

**Comment by embeddedt** [comment] 2024-01-04 20:53
What mod are you using to make the vanilla glass have connected textures?

**Comment by GarthF** [comment] 2024-01-04 21:00
I'm not sure what's being used for that, I'll trawl through the direwolf20 pack and see if I can spot anything.

**Comment by GarthF** [comment] 2024-01-04 21:09
So, did some digging. Xycraft: Override looks like the mod thats doing it. Provides override textures for glass

**Comment by embeddedt** [comment] 2024-01-04 21:10
Thanks. I looked through the mod list and saw the same thing, and I can indeed reproduce with just Xycraft's stuff installed.

**Comment by embeddedt** [comment] 2024-01-04 21:32
I found the problem and solved it in the latest change to #529; when that is merged and released, XyCraft's overrides will not break shadows anymore.

**Closed as completed** 2024-02-01 20:42 UTC
Labels: bug
