### ISSUE TITLE
Update 1.20.1 version 1.7.5 please 

### ISSUE THREAD

**Issue by NumpaMC** [Asek3/Oculus#707] opened 2024-10-23 01:08 UTC
Distant horizons not support oculus version 1.7.0

**Comment by mpustovoi** [comment] 2024-10-23 17:35
Duplicate of https://github.com/Asek3/Oculus/issues/683.

The pull request with the fix was already merged about two weeks ago. It remains only to wait for the release.

**Closed as completed** 2024-10-28 11:10 UTC
Labels: enhancement
