### ISSUE TITLE
Bizzaire crash when using Oculus doesn't reach main menu.

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Asek3/Oculus#22] opened 2022-03-30 14:20 UTC
Crash log - https://paste.vcnet.work/tQuQuV5WUO

**Comment by TylerPos** [comment] 2022-03-31 22:59
This is caused by the other issue I have just posted. The current version of Oculus on 1.18.1 is incompatible with flywheel 0.6.1, you need to downgrade to 0.6.0 (which may break other mods) to use oculus.

**Comment by VirtualGaming1** [comment] 2022-04-01 21:59
Just want to let the mod author know that I will be waiting for an update.

+1 for update fix

**Comment by TylerPos** [comment] 2022-04-01 23:41
It unfortunately wont be fixed as the mod author has stated he has no intentions on updating the fix to 1.18.1 @VirtualGaming1

**Comment by TylerPos** [comment] 2022-04-01 23:42
> Just want to let the mod author know that I will be waiting for an update.
> 
> +1 for update fix

It unfortunately wont be fixed as the mod author has stated he has no intentions on updating the fix to 1.18.1 @VirtualGaming1

**Comment by Asek3** [comment] 2022-04-02 10:08
1.18.1 Version is not supported

**Closed by Asek3** 2022-04-02 10:08 UTC
