### ISSUE TITLE
Oculus 1.7.0 crash. Downgrade to 1.6.15a remains stable.

### ISSUE THREAD

**Issue by skellitor301** [Asek3/Oculus#692] opened 2024-09-17 20:01 UTC
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.31+mc1.20.1.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3080

### Java Version

Java 17

### Reproduction Steps

Oculus 1.7.0 produces a crash on startup with the mods listed in crash report. However Oculus 1.6.15a does not crash on startup and will allow the game to be played. Mod list does include Distant Horizons and Create.

### Crash Report file and latest.log

```shell
https://mclo.gs/1qak1bx
```

### Additional context

I'm including the logs for the successful launch of the game with Oculus 1.6.15a here: https://mclo.gs/AtR2FmQ
In hopes that this helps determine what changes between 1.6.15a and 1.7.0 is causing the incompatibility.

**Comment by mpustovoi** [comment] 2024-09-20 11:06
Duplicate of https://github.com/Asek3/Oculus/issues/683.
Oculus 1.7.0 is incompatible with Distant Horizons 2.2.X for now.
Downgrade DH to [2.1.2-a - 1.20.1 forge/fabric](https://modrinth.com/mod/distanthorizons/version/2.1.2-a-1.20.1) until a fix is released from Oculus.

**Comment by skellitor301** [comment] 2024-09-20 21:29
Yep, I more just wanted to post this info in case it does help figure out the issue. Since Oculus 1.6.15a does work with DH 2.2.x, the hope was knowing the changes between the two versions of Oculus would help narrow down the search.

**Comment by mpustovoi** [comment] 2024-09-20 21:36
I think that a partial 'rollback' of the version won't happen.
I've also saw in the DH issues that Oculus is somehow incorrectly interacting with it. Something like "Oculus invades DH with its mixins instead of using the DH API".
Perhaps this leads to problems for Oculus with the release of DH updates.

**Comment by skellitor301** [comment] 2024-09-21 20:31
It's less I'm suggesting a solution since I'm unfamiliar with the code and language, and more helping to narrow the change(s) that are causing the incompatibility. While I know a partial rollback might not be ideal, at least it can be confirmed that there are compatible and not-compatible versions so the issue can at least be narrowed down.

I'm not here to discuss a solution, because again, I'm unfamiliar with the code and am not a contributor. I'm just here to make a report that is relevant to the issue, and knowing a bit about coding can determine that at least knowing that the current version of DH can work with a version of Oculus is a big deal. Just knowing a working version exists is valuable info, especially when it comes to debugging the issue and figuring out potential causes. That is all this report was meant to do. I do not know enough of the code base nor the language it's written in to come up with solutions. If I did I would just fork the code and commit a fix myself that the devs could implement.

**Closed as not planned** 2024-10-30 15:51 UTC
Labels: bug, invalid

**Comment by Lunawolfs85** [comment] 2026-07-07 18:11
Use version of embeddium 0.3.2.8 no error so far
