### ISSUE TITLE
Small dots appearing when using shaders

### ISSUE THREAD

**Issue by inverspe** [Asek3/Oculus#76] opened 2022-05-03 14:35 UTC
### What happened?

I used complementary shaders and 4-6 dots appear in my screen. I haven't tried other shaders yet.

they never go away it also changes colors depending where you are looking at.

the dots changes position often

### Minecraft Version

1.18.2

### Iris Version

Latest version of Oculus

### Sodium Version

Latest version of Rubidium

### Operating System

Windows 10

### What is your GPU?

Radeon RX 570 Series

### Java Version

Java 8

### Additional context

mods that im running are
1.Clumps
2.Create
3.farmers delight
4.flywheel
5.fps reducer
6. just enough items
7. Lazy DFU
8. Oculus
9. Rubidium
10. Starlight

**Comment by MeycsHD** [comment] 2022-05-03 16:51
I have the same issue. I tried another shader but its still there

**Comment by onspeed8** [comment] 2022-05-06 15:48
Same here, happens with all shaders. Dots appear at random locations in my screen and appear to be moving over time (even if i don't move my character/screen at all)
The dots seem to be some sort of see-through, allowing me to see the skybox through them.

only thing i figured out that might be usefull is that it has something to do with shadows.
changing the shadowmap resolution also directly affects the size of the dots.
and turning shadows off removes them.

**Comment by eilamg** [comment] 2022-05-07 00:33
Can confirm these are sky-colored artifacts that appear when using Complementary Shaders with real-time shadows turned on.

From some quick testing done so far:

1. Was unable to reproduce issue with OptiFine, using the same mod and shader configuration.
2. Was unable to reproduce issue on an otherwise unmodded instance.
3. Was unable to reproduce issue on a flat map (i.e no modded worldgen blocks).

The above lead me to believe this is an Oculus-specific issue (or possibly Rubidium), and it likely has something to do with some specific modded worldgen blocks. I'll try to investigate further, see if I can pinpoint the culprit.

**Comment by eilamg** [comment] 2022-05-07 00:57
So the most likely candidate was it - Flywheel (the Create dependency rendering library). Flywheel has built-in functionality to turn its own rendering optimizations off when it detects OptiFine, but that doesn't trigger with Oculus.

Turning it off manually with `/flywheel backend off` solves the issue.

**Comment by aethaerya** [comment] 2022-05-09 15:46
Since no one has posted a picture of what these look like,
![image](https://user-images.githubusercontent.com/28931355/167447389-b28a63c3-abaa-4453-aa56-0eeefe9f2d43.png)

**Comment by Arcitect-X** [comment] 2022-05-26 18:05
I have this issue as well with rubidium/oculus and in conjuction with sildurs/BSL and seus.   This is occurring in All the mods 7 modpack 1.18.2. This pack has flywheel as well.  Note the pixels on bottom right of lower furnace and larger dots closest to lower left on upper furnace.   When shaders are disabled it goes away.   Can confirm the command:` /flywheel backend off` fixes issue
![Base Profile Screenshot 2022 05 26 - 14 02 37 92](https://user-images.githubusercontent.com/72455380/170548553-7a23bb73-b10e-4de2-b7b1-206da7fb8819.png)

**Comment by Asek3** [comment] 2022-08-15 18:15
Should be fixed on latest Flywheel and Oculus versions. If not, plz tell

**Closed as completed by Asek3** 2022-08-15 18:15 UTC
Labels: bug
